name: Update package version
on:
  pull_request:
    branches:
      - develop
      - release/*
    types:
      - closed
      - synchronize

jobs:
  publish_patch:
    if: github.event.pull_request.merged == true
    name: Update Package Version
    runs-on: ubuntu-latest

    steps:
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config --global user.name "Release manager"
          git config --global user.email noreply@github.com

      - name: Update version in package.json
        uses: ./.github/actions/bump-version
        id: bump
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
