name: Release start
on:
  milestone:
    types:
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get -y install git-flow

      - name: Set up Node.js
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@cytiva"

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Initialize mandatory git config
        run: |
          git config user.name "Release manager"
          git config user.email noreply@github.com

      - name: Init git flow
        run: |
          git checkout master
          git checkout develop
          git flow init -d

      - name: Release start
        run: |
          git flow release start ${{ github.event.milestone.title }}

      - name: Bump package.json version to prerelease
        working-directory: ./projects/cui-design-ng
        run: |
          npm version --git-tag-version=false ${{ github.event.milestone.title }}-0

      - name: Commit changes
        run: |
          git commit -a -m "ci: version bump to ${{ github.event.milestone.title }}-0"

      - name: Release publish
        run: |
          git flow release publish

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.milestone.title }}
          base: master
          title: release/${{ github.event.milestone.title }}
          body: |
            Generated by closing milestone ${{ github.event.milestone.title }}
